steps:
  - name: ':docker:'
    plugins:
      'docker-compose#v3.0.0':
        build: ci
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v3.0.0':
        run: ci
    agents:
      queue: workers
  - name: ':jest:'
    command: yarn jest
    plugins:
      'docker-compose#v3.0.0':
        run: ci
    agents:
      queue: workers
